// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreePassBot2.Data;

#nullable disable

namespace TreePassBot2.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251220120005_AddAutoCleanupJob")]
    partial class AddAutoCleanupJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreePassBot2.Core.Entities.ArchivedMessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsWithdrawed")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("OperatorId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserNickName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserNickName");

                    b.HasIndex("GroupId", "UserId");

                    b.ToTable("ArchivedMessageLogs");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.AuditRequestData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ProcessedBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("VerificationCode");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("AuditRequests");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.GroupInfo", b =>
                {
                    b.Property<decimal>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.MessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RecalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("RecalledBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SendAt");

                    b.HasIndex("UserName");

                    b.HasIndex("GroupId", "UserId", "SendAt");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.PluginState", b =>
                {
                    b.Property<string>("PluginId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("StateDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PluginId", "Scope", "GroupId", "UserId");

                    b.ToTable("PluginStates");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.QqUserInfo", b =>
                {
                    b.Property<decimal>("QqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("QqId");

                    b.HasIndex("QqId")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
