// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreePassBot2.Data;

#nullable disable

namespace TreePassBot2.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreePassBot2.Core.Entities.ArchivedMessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchiveReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecalledBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SendAt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SendAt"), "brin");

                    b.HasIndex("GroupId", "MessageId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("GroupId", "MessageId"), new[] { "UserId", "SendAt" });

                    b.ToTable("ArchivedMessageLogs");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.AuditRequestData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsJoinedGroup")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ProcessedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("AuditRequests");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.GroupInfo", b =>
                {
                    b.Property<long>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GroupId"));

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups", t =>
                        {
                            t.HasCheckConstraint("CK_Group_Id_Positive", "\"GroupId\" > 0");
                        });
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.MessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("boolean");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RecalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RecalledBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SendAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SendAt");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SendAt"), "brin");

                    b.HasIndex("GroupId", "MessageId");

                    b.HasIndex("GroupId", "SendAt");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.PluginState", b =>
                {
                    b.Property<string>("PluginId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PluginId", "Scope", "GroupId", "UserId");

                    b.HasIndex("StateDataJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StateDataJson"), "gin");

                    b.ToTable("PluginStates");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.QqUserInfo", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InternalId"));

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("QqId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InternalId");

                    b.HasIndex("GroupId");

                    b.HasIndex("QqId", "GroupId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.AuditRequestData", b =>
                {
                    b.HasOne("TreePassBot2.Core.Entities.GroupInfo", "Group")
                        .WithMany("AuditRequests")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.MessageLog", b =>
                {
                    b.HasOne("TreePassBot2.Core.Entities.GroupInfo", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.QqUserInfo", b =>
                {
                    b.HasOne("TreePassBot2.Core.Entities.GroupInfo", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TreePassBot2.Core.Entities.GroupInfo", b =>
                {
                    b.Navigation("AuditRequests");

                    b.Navigation("Members");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
